saturn.localisation_and_units = {
	mod_origin = {name = "Mod origin", format_numeric = "%d", units = ""},
	sound_spec_loop = {hidden = true},
	tiles = {hidden = true},
	description = {hidden = true},
	inventory_image = {hidden = true},
	tool_capabilities = {hidden = true},
        wield_image = {hidden = true},
	sounds = {hidden = true},
	legacy_mineral = {hidden = true},
        stack_max = {hidden = true},
	on_drop = {hidden = true},
	on_secondary_use = {hidden = true},
	on_use = {hidden = true},
	on_place = {hidden = true},
	on_construct = {hidden = true},
	on_punch = {hidden = true},
	on_net_form = {hidden = true},
	on_net_power_change = {hidden = true},
	groups = {hidden = true},
	after_place_node = {hidden = true},
	on_destruct = {hidden = true},
	on_timer = {hidden = true},
	can_dig = {hidden = true},
	on_dig = {hidden = true},
	after_place_node = {hidden = true},
	after_dig_node = {hidden = true},
	allow_metadata_inventory_move = {hidden = true},
        allow_metadata_inventory_put = {hidden = true},
        allow_metadata_inventory_take = {hidden = true},
        on_metadata_inventory_move = {hidden = true},
        on_metadata_inventory_put = {hidden = true},
        on_metadata_inventory_take = {hidden = true},
	on_receive_fields = {hidden = true},
	sound_spec_single_shot = {hidden = true},
	create_hit_effect = {hidden = true},
	possible_modifications = {hidden = true},
	use_texture_alpha = {hidden = true},
	sunlight_propagates  = {hidden = true},
	drawtype = {hidden = true},
	mesh = {hidden = true},
	walkable = {hidden = true},
	pointable = {hidden = true},
	diggable = {hidden = true},
	drop = {hidden = true},
	paramtype = {hidden = true},
	paramtype2 = {hidden = true},
	post_effect_color = {hidden = true},
	collision_box = {hidden = true},
	delivery_address = {name = "Destination space station", format_numeric = "%d", units = ""},
	sending_date = {name = "Sending date", format_proc = saturn.date_to_string, units = ""},
	delivery_term = {name = "Delivery term", format_proc = saturn.date_to_string, units = ""},
	urgency_class = {name = "Urgency class", format_numeric = "%d", units = ""},
	reward = {name = "Reward", format_numeric = "%d", units = " Cr. (10 Cr. in case delivery term was overdue by 100%)"},
	toughness = {name = "Toughness", format_numeric = "%d", units = ""},
	type = {hidden = true},
	name = {hidden = true},
	equipment_slot = {name = "Equipment type", format_numeric = "%d", units = ""},
	light_source = {name = "Light source power", format_numeric = "%d", units = "W"},
	price = {name = "Price", format_numeric = "%4.1f", units = "Cr. (selling price is 70% from current price)"},
	is_market_item = {name = "Can be found on market"},
	is_ore = {name = "Can be found on ore market"},
	is_microfactory = {name = "Microfactory"},
	is_enemy_item = {name = "Is enemy part"},
	max_wear = {name = "Durability", format_numeric = "%d", units = ""},
	rated_power = {name = "Rated power", format_numeric = "%4.1f", units = "MW"},
	generated_power = {name = "Generated power", format_numeric = "%4.1f", units = "MW"},
	use_ammo_type = {name = "Ammo type"},
	use_ammo_amount = {name = "Ammo amount shooted per cooldown", format_numeric = "%d", units = "bullets"},
	cooldown  = {name = "Cooldown time", format_numeric = "%4.2f", units = "s"},
	volume = {name = "Volume", format_numeric = "%4.2f", units = "cubic meters"},
	damage = {name = "Damage per shot", format_numeric = "%4.1f", units = ""},
	weight = {name = "Weight", format_numeric = "%d", units = "kg"},
	last_ammo_slot = {name = "Last inventory slot used for ammo", units = ""},
	time_of_last_shoot = {hidden = true},
	weapon_slots = {name = "Active equipment slots", format_numeric = "%d", units = ""},
	hold_slots = {name = "Hold slots", format_numeric = "%d", units = ""},
	radar_slots = {name = "Radar slots", format_numeric = "%d", units = ""},
	scaner_slots = {name = "Scaner slots", format_numeric = "%d", units = ""},
	engine_slots = {name = "Engine slots", format_numeric = "%d", units = ""},
	droid_slots = {name = "Droid slots", format_numeric = "%d", units = ""},
	power_generator_slots = {name = "Power generator slots", format_numeric = "%d", units = ""},
	special_equipment_slots = {name = "Special equipment slots", format_numeric = "%d", units = ""},
	forcefield_generator_slots = {name = "Forcefield generator slots", format_numeric = "%d", units = ""},
	player_visual = {hidden = true},
	free_space = {name = "Free space in hold", format_numeric = "%4.1f", units = "cubic meters"},
	droid_efficiency = {name = "Droid efficiency", format_numeric = "%d", units = "pt./s"},
	gauss_ammo = {name = "Ammo for Gauss MG"},
	damage_modificator = {name = "Damage multiplier", format_numeric = "%4.1f", units = ""},
	traction = {name = "Traction", format_numeric = "%d", units = "N"},
	range = {name = "Range of interaction with outer space", format_numeric = "%4.0f", units = "m"},
	action_range = {name = "Range of action", format_numeric = "%4.0f", units = "m"},
	noise_offset = {name = "Rarity (-1.0 - common, -2.0 - very rare)", format_numeric = "%4.1f", units = ""},
	destructible_by_weapons = {name = "Fragile (destructible by bullets)"},
	single_per_player = {name = "Only single one can be mounted per player"},
	cycle_time = {name = "Cycle time", format_numeric = "%4.0f", units = "s"},
	forcefield_protection = {name = "Forcefield damage absorption", format_numeric = "%4.1f", units = "%"},
	loot_level = {name = "Loot level", format_numeric = "%d", units = ""},
	radar_range = {name = "Radar radius", format_numeric = "%d", units = "m"},
}

saturn.localisation_and_units_special = {
	rated_power = {format_numeric = "%+4.1f"},
	generated_power = {format_numeric = "%+4.1f"},
	cooldown  = {format_numeric = "%+4.1f"},
	volume = {format_numeric = "%+4.2f"},
	damage = {format_numeric = "%+4.2f"},
	weight = {format_numeric = "%+d"},
	last_ammo_slot = {format_numeric = "%d"},
	weapon_slots = {format_numeric = "%+d"},
	hold_slots = {format_numeric = "%+d"},
	radar_slots = {format_numeric = "%+d"},
	scaner_slots = {format_numeric = "%+d"},
	engine_slots = {format_numeric = "%+d"},
	droid_slots = {format_numeric = "%+d"},
	power_generator_slots = {format_numeric = "%+d"},
	special_equipment_slots = {format_numeric = "%+d"},
	forcefield_generator_slots = {format_numeric = "%+d"},
	free_space = {format_numeric = "%+4.2f"},
	droid_efficiency = {format_numeric = "%+4.1f"},
	traction = {format_numeric = "%+d"},
	range = {format_numeric = "%+4.1f"},
	action_range = {format_numeric = "%+4.1f"},
	noise_offset = {format_numeric = "%+4.1f"},
	cycle_time = {format_numeric = "%+4.0f"},
	forcefield_protection = {format_numeric = "%+4.2f"},
	radar_range = {format_numeric = "%+d"},
}

local function testdata()
    local key,value
    local incorrect=false
    for key,value in pairs(saturn.localisation_and_units_special) do
	if saturn.localisation_and_units[key] == nil then
		error(
		    "Key " .. key .. " has record in saturn."..
		    "localisation_and_units_special but not in "..
		    "saturn.localisation_and_units"
		)
	end
    end
end
testdata()
